/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auctions/{auctionId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 판매 포기
         * @description 경매 실패/유찰 시 상품을 더 이상 경매에 올리지 않습니다.
         */
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/relist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 재경매 등록
         * @description 유찰되거나 결제 실패한 경매 상품을 다시 등록합니다. (판매자 전용)
         */
        post: operations["relistAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관심 경매 등록
         * @description 특정 경매를 관심 목록에 추가합니다
         */
        post: operations["addBookmark"];
        /**
         * 관심 경매 해제
         * @description 특정 경매를 관심 목록에서 제거합니다
         */
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 입찰 기록 조회
         * @description 해당 경매의 실시간 입찰 내역(로그)을 조회합니다.
         */
        get: operations["getBids"];
        put?: never;
        /**
         * 입찰하기
         * @description 특정 경매에 입찰을 진행합니다. (판매자 본인 입찰 불가)
         */
        post: operations["createBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{productId}/startTime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 검수승인 후 경매일정 확정
         * @description 관리자가 검수 승인 후 해당상품의 경매일정을 확정합니다.
         */
        patch: operations["deterMineStartAuction"];
        trace?: never;
    };
    "/api/v1/members/me/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나의 판매 내역 조회
         * @description 내가 등록한 경매 물품 목록을 필터(진행중/종료 등)에 따라 조회합니다. (판매자 권한 필요)
         */
        get: operations["getMySales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나의 낙찰(주문) 목록 조회
         * @description 내가 낙찰받은 경매 목록을 결제 상태(대기/완료)에 따라 조회합니다.
         */
        get: operations["getMyAuctionOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 관심 경매 목록 조회
         * @description 내가 찜한 경매 목록을 조회합니다
         */
        get: operations["getMyBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나의 입찰 내역 조회
         * @description 내가 참여한 경매 입찰 목록을 상태별로 조회합니다.
         */
        get: operations["getMyBids"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 목록 조회
         * @description 검색 조건(키워드, 카테고리, 상태)과 정렬 조건에 따라 경매 목록을 조회합니다.
         */
        get: operations["getAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 상세 조회
         * @description 경매의 상세 정보를 조회합니다. (로그인 시 내 입찰 내역 포함)
         */
        get: operations["getAuctionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/subscribers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 특정 경매 구독자 수 조회
         * @description 특정 경매 구독자 수를 조회합니다. (모니터링용)
         */
        get: operations["getAuctionSubscribers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 실시간 입찰 이벤트 구독
         * @description 경매 실시간 입찰 이벤트를 구독합니다.
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 낙찰 상세 정보 조회
         * @description 경매 종료 후 낙찰 정보를 조회합니다. (구매자/판매자만 조회 가능)
         */
        get: operations["getAuctionOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/subscribers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 구독자 수 조회
         * @description 전체 구독자 수를 조회합니다. (모니터링용)
         */
        get: operations["getTotalSubscribers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuctionWithdrawResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** @enum {string} */
            beforeStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** @enum {string} */
            currentStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            message?: string;
        };
        SuccessResponseDtoAuctionWithdrawResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionWithdrawResponseDto"];
        };
        AuctionRelistRequestDto: {
            /** Format: int64 */
            startPrice?: number;
            /** Format: int64 */
            tickSize?: number;
            /** Format: int32 */
            durationDays?: number;
        };
        AuctionRelistResponseDto: {
            /** Format: int64 */
            newAuctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            message?: string;
        };
        SuccessResponseDtoAuctionRelistResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionRelistResponseDto"];
        };
        AuctionAddBookmarkResponseDto: {
            bookmarked?: boolean;
            /** Format: int64 */
            auctionId?: number;
        };
        SuccessResponseDtoAuctionAddBookmarkResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionAddBookmarkResponseDto"];
        };
        BidRequestDto: {
            /** Format: int64 */
            bidAmount: number;
        };
        BidResponseDto: {
            /** Format: int64 */
            bidId?: number;
            /** Format: int64 */
            auctionId?: number;
            publicId?: string;
            /** Format: date-time */
            bidTime?: string;
            /** Format: int64 */
            bidAmount?: number;
            /** Format: int64 */
            updatedCurrentPrice?: number;
        };
        SuccessResponseDtoBidResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BidResponseDto"];
        };
        SuccessResponseDtoLong: {
            /** Format: int32 */
            status?: number;
            message?: string;
            /** Format: int64 */
            data?: number;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        MySaleResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            title?: string;
            thumbnailUrl?: string;
            /** Format: int64 */
            currentPrice?: number;
            /** Format: int32 */
            bidCount?: number;
            /** @enum {string} */
            auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** @enum {string} */
            tradeStatus?: "PROCESSING" | "SUCCESS" | "FAILED";
            /** Format: date-time */
            endTime?: string;
            actionRequired?: boolean;
        };
        PageDto: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        PagedResponseDtoMySaleResponseDto: {
            data?: components["schemas"]["MySaleResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        MyAuctionOrderListResponseDto: {
            /** Format: int64 */
            orderId?: number;
            /** Format: int64 */
            auctionId?: number;
            productName?: string;
            thumbnailUrl?: string;
            /** Format: int32 */
            finalPrice?: number;
            /** @enum {string} */
            orderStatus?: "PROCESSING" | "SUCCESS" | "FAILED";
            statusDescription?: string;
            /** Format: date-time */
            tradeDate?: string;
            auctionRequired?: boolean;
        };
        PagedResponseDtoMyAuctionOrderListResponseDto: {
            data?: components["schemas"]["MyAuctionOrderListResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionBookmarkListResponseDto: {
            /** Format: int64 */
            bookmarkId?: number;
            auctionInfo?: components["schemas"]["AuctionListResponseDto"];
        };
        AuctionListResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            productName?: string;
            thumbnailUrl?: string;
            category?: string;
            /** Format: int32 */
            currentPrice?: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            bidsCount?: number;
            /** @enum {string} */
            auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** Format: date-time */
            endTime?: string;
        };
        PagedResponseDtoAuctionBookmarkListResponseDto: {
            data?: components["schemas"]["AuctionBookmarkListResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        MyBidResponseDto: {
            /** Format: int64 */
            bidId?: number;
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            bidAmount?: number;
            /** Format: date-time */
            bidTime?: string;
            /** @enum {string} */
            auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** Format: int64 */
            currentPrice?: number;
            /** Format: date-time */
            endTime?: string;
        };
        PagedResponseDtoMyBidResponseDto: {
            data?: components["schemas"]["MyBidResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionSearchCondition: {
            ids?: number[];
            keyword?: string;
            /** @enum {string} */
            category?: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** @enum {string} */
            sort?: "CLOSING_SOON" | "NEWEST";
        };
        PagedResponseDtoAuctionListResponseDto: {
            data?: components["schemas"]["AuctionListResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionDetailResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            productName?: string;
            productDescription?: string;
            imageUrls?: string[];
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int64 */
            remainingSeconds?: number;
            price?: components["schemas"]["PriceInfo"];
            bid?: components["schemas"]["BidInfo"];
            myParticipation?: components["schemas"]["MyParticipationInfo"];
        };
        BidInfo: {
            canBid?: boolean;
            /** Format: int32 */
            minBidPrice?: number;
            /** Format: int64 */
            highestBidderId?: number;
            isMyHighestBid?: boolean;
            isSeller?: boolean;
        };
        MyParticipationInfo: {
            hasBid?: boolean;
            /** Format: int32 */
            myLastBidPrice?: number;
        };
        PriceInfo: {
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            currentPrice?: number;
            /** Format: int32 */
            tickSize?: number;
        };
        SuccessResponseDtoAuctionDetailResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionDetailResponseDto"];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        AuctionOrderResponseDto: {
            /** Format: int64 */
            orderId?: number;
            /** Format: int64 */
            auctionId?: number;
            viewerRole?: string;
            /** @enum {string} */
            orderStatus?: "PROCESSING" | "SUCCESS" | "FAILED";
            statusDescription?: string;
            /** Format: date-time */
            createdAt?: string;
            productInfo?: components["schemas"]["ProductInfo"];
            paymentInfo?: components["schemas"]["PaymentInfo"];
            trader?: components["schemas"]["TraderInfo"];
            shippingInfo?: components["schemas"]["ShippingInfo"];
        };
        PaymentInfo: {
            /** Format: int32 */
            finalPrice?: number;
            /** Format: int32 */
            depositUsed?: number;
            /** Format: int32 */
            paymentAmount?: number;
        };
        ProductInfo: {
            title?: string;
            thumbnailUrl?: string;
        };
        ShippingInfo: {
            receiverName?: string;
            address?: string;
            trackingNumber?: string;
        };
        SuccessResponseDtoAuctionOrderResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionOrderResponseDto"];
        };
        TraderInfo: {
            nickname?: string;
            contact?: string;
        };
        BidLogResponseDto: {
            /** Format: int64 */
            id?: number;
            publicId?: string;
            /** Format: date-time */
            bidTime?: string;
            /** Format: int64 */
            bidAmount?: number;
        };
        PagedResponseDtoBidLogResponseDto: {
            data?: components["schemas"]["BidLogResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionRemoveBookmarkResponseDto: {
            removed?: boolean;
            /** Format: int64 */
            auctionId?: number;
        };
        SuccessResponseDtoAuctionRemoveBookmarkResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionRemoveBookmarkResponseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionWithdrawResponseDto"];
                };
            };
        };
    };
    relistAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionRelistRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionRelistResponseDto"];
                };
            };
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionAddBookmarkResponseDto"];
                };
            };
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionRemoveBookmarkResponseDto"];
                };
            };
        };
    };
    getBids: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoBidLogResponseDto"];
                };
            };
        };
    };
    createBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoBidResponseDto"];
                };
            };
        };
    };
    deterMineStartAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoLong"];
                };
            };
        };
    };
    getMySales: {
        parameters: {
            query: {
                filter?: "ALL" | "ONGOING" | "COMPLETED" | "ACTION_REQUIRED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoMySaleResponseDto"];
                };
            };
        };
    };
    getMyAuctionOrders: {
        parameters: {
            query: {
                status?: "PROCESSING" | "SUCCESS" | "FAILED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoMyAuctionOrderListResponseDto"];
                };
            };
        };
    };
    getMyBookmarks: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoAuctionBookmarkListResponseDto"];
                };
            };
        };
    };
    getMyBids: {
        parameters: {
            query: {
                auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoMyBidResponseDto"];
                };
            };
        };
    };
    getAuctions: {
        parameters: {
            query: {
                condition: components["schemas"]["AuctionSearchCondition"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoAuctionListResponseDto"];
                };
            };
        };
    };
    getAuctionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionDetailResponseDto"];
                };
            };
        };
    };
    getAuctionSubscribers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getAuctionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionOrderResponseDto"];
                };
            };
        };
    };
    getTotalSubscribers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
}
