/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/members/me/seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 판매자 인증
         * @description 저장된 정보를 기반으로 SELLER로 업데이트 합니다
         */
        post: operations["promoteSeller"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 본인 조회
         * @description 본인의 정보를 조회합니다.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 회원 본인 수정
         * @description 본인의 정보를 수정합니다.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/members/me/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 회원 본인인증 정보 수정
         * @description 본인의 연락처/실명 정보를 수정합니다.
         */
        patch: operations["updateIdentity"];
        trace?: never;
    };
    "/api/v1/members/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 입찰시 필수 정보 존재 확인
         * @description 회원 입찰시 필요 정보(주소, 본인인증) 존재 확인
         */
        get: operations["verifyParticipation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponseDtoVoid: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: unknown;
        };
        MemberUpdateRequestDto: {
            nickname?: string;
            intro?: string;
            zipCode?: string;
            address?: string;
            addressDetail?: string;
            clearFields?: ("INTRO" | "ZIPCODE" | "ADDRESS" | "ADDRESS_DETAIL")[];
        };
        MemberUpdateResponseDto: {
            publicId?: string;
            email?: string;
            nickname?: string;
            intro?: string;
            address?: string;
            addressDetail?: string;
            zipCode?: string;
            contactPhone?: string;
            realName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SuccessResponseDtoMemberUpdateResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MemberUpdateResponseDto"];
        };
        MemberUpdateIdentityRequestDto: {
            realName?: string;
            contactPhone?: string;
        };
        MemberMeResponseDto: {
            publicId?: string;
            role?: string;
            email?: string;
            nickname?: string;
            intro?: string;
            address?: string;
            addressDetail?: string;
            zipCode?: string;
            contactPhoneMasked?: string;
            realNameMasked?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SuccessResponseDtoMemberMeResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MemberMeResponseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    promoteSeller: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberMeResponseDto"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberUpdateResponseDto"];
                };
            };
        };
    };
    updateIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateIdentityRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberUpdateResponseDto"];
                };
            };
        };
    };
    verifyParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
}
