/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markAsRead"];
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUnreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponseDtoVoid: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: unknown;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        NotificationResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            message?: string;
            link?: string;
            isRead?: boolean;
            type?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageDto: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        PagedResponseDtoNotificationResponseDto: {
            data?: components["schemas"]["NotificationResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        SuccessResponseDtoPagedResponseDtoNotificationResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PagedResponseDtoNotificationResponseDto"];
        };
        NotificationUnreadCountResponseDto: {
            /** Format: int64 */
            count?: number;
        };
        SuccessResponseDtoNotificationUnreadCountResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["NotificationUnreadCountResponseDto"];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query: {
                onlyUnread?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPagedResponseDtoNotificationResponseDto"];
                };
            };
        };
    };
    getUnreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoNotificationUnreadCountResponseDto"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
}
