/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/payments/settlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정산 배치 실행
         * @description 정산 배치를 실행합니다.
         */
        post: operations["runSettlementJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 요청
         * @description 토스페이먼츠 결제를 요청합니다
         */
        post: operations["requestPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/charges/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 승인
         * @description 토스페이먼츠 결제 승인 후 지갑에 충전합니다
         */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 낙찰 결제
         * @description 낙찰자가 최종 결제를 완료합니다 (보증금 + 잔금)
         */
        post: operations["auctionFinalPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/me/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 지갑 조회
         * @description 내 지갑 정보를 조회합니다.
         */
        get: operations["getMyWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/me/wallet-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지갑 거래 내역 조회
         * @description 지갑 거래 내역을 조회합니다.
         */
        get: operations["getWalletTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/me/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 정산 내역 조회
         * @description 정산 내역을 조회합니다.
         */
        get: operations["getSettlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponseDtoVoid: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: unknown;
        };
        PaymentRequestDto: {
            /** Format: int32 */
            amount: number;
        };
        PaymentRequestResponseDto: {
            orderId?: string;
            /** Format: int32 */
            amount?: number;
            customerName?: string;
            customerEmail?: string;
        };
        SuccessResponseDtoPaymentRequestResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PaymentRequestResponseDto"];
        };
        PaymentConfirmRequestDto: {
            paymentKey: string;
            orderId: string;
            /** Format: int32 */
            amount: number;
        };
        PaymentConfirmResponseDto: {
            orderId?: string;
            /** Format: int32 */
            amount?: number;
            /** Format: int32 */
            balance?: number;
        };
        SuccessResponseDtoPaymentConfirmResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PaymentConfirmResponseDto"];
        };
        AuctionFinalPaymentRequestDto: {
            receiverName: string;
            phone: string;
            zipCode: string;
            address: string;
            addressDetail?: string;
            message?: string;
        };
        AuctionFinalPaymentResponseDto: {
            /** Format: int64 */
            paymentId?: number;
            /** Format: int64 */
            auctionId?: number;
            buyerId?: string;
            /** Format: int32 */
            finalPrice?: number;
            /** Format: int32 */
            depositAmount?: number;
            /** Format: int32 */
            paidAmount?: number;
            /** Format: int32 */
            balanceAfter?: number;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SuccessResponseDtoAuctionFinalPaymentResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionFinalPaymentResponseDto"];
        };
        SuccessResponseDtoWalletResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["WalletResponseDto"];
        };
        WalletResponseDto: {
            /** Format: int64 */
            id?: number;
            publicId?: string;
            /** Format: int32 */
            balance?: number;
            /** Format: int32 */
            holdingAmount?: number;
        };
        PageDto: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        PagedResponseDtoWalletTransactionResponseDto: {
            data?: components["schemas"]["WalletTransactionResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        SuccessResponseDtoPagedResponseDtoWalletTransactionResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PagedResponseDtoWalletTransactionResponseDto"];
        };
        WalletTransactionResponseDto: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "TOPUP_DONE" | "DEPOSIT_HOLD" | "DEPOSIT_RELEASE" | "DEPOSIT_USED" | "DEPOSIT_FORFEITED" | "AUCTION_PAYMENT" | "REFUND_DONE" | "SETTLEMENT_PAID" | "SETTLEMENT_FEE";
            typeName?: string;
            /** Format: int32 */
            balanceDelta?: number;
            /** Format: int32 */
            holdingDelta?: number;
            /** Format: int32 */
            balance?: number;
            /** Format: int32 */
            holdingAmount?: number;
            /** @enum {string} */
            referenceType?: "PAYMENT" | "DEPOSIT" | "AUCTION_ORDER" | "SETTLEMENT" | "REFUND";
            /** Format: int64 */
            referenceId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PagedResponseDtoSettlementResponseDto: {
            data?: components["schemas"]["SettlementResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        SettlementResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            sellerId?: number;
            /** Format: int32 */
            salesAmount?: number;
            /** Format: int32 */
            feeAmount?: number;
            /** Format: int32 */
            settlementAmount?: number;
            productName?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SuccessResponseDtoPagedResponseDtoSettlementResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PagedResponseDtoSettlementResponseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runSettlementJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    requestPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPaymentRequestResponseDto"];
                };
            };
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPaymentConfirmResponseDto"];
                };
            };
        };
    };
    auctionFinalPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionFinalPaymentRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionFinalPaymentResponseDto"];
                };
            };
        };
    };
    getMyWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoWalletResponseDto"];
                };
            };
        };
    };
    getWalletTransactions: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                transactionType?: "TOPUP_DONE" | "DEPOSIT_HOLD" | "DEPOSIT_RELEASE" | "DEPOSIT_USED" | "DEPOSIT_FORFEITED" | "AUCTION_PAYMENT" | "REFUND_DONE" | "SETTLEMENT_PAID" | "SETTLEMENT_FEE";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPagedResponseDtoWalletTransactionResponseDto"];
                };
            };
        };
    };
    getSettlements: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: "READY" | "DONE" | "CANCELED" | "FAILED";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPagedResponseDtoSettlementResponseDto"];
                };
            };
        };
    };
}
