/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 상품 등록
         * @description 새로운 상품을 등록합니다
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/recommendations/internal-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 내부시세 기반 AI 시작가 추천
         * @description AI를 사용하여 유사 상품이 외부에서 가격이 어느정도에 형성되어있는지 알려줍니다.
         */
        post: operations["getInternalPriceGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/recommendations/external-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 외부시세 기반 AI 시작가 추천
         * @description AI를 사용하여 유사 상품이 외부에서 가격이 어느정도에 형성되어있는지 알려줍니다.
         */
        post: operations["getExternalPriceGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 검수를 위한 전체 상품목록 조회
         * @description 관리자가 상품 검수 처리를 위해 모든 상품정보를 조회합니다.
         */
        get: operations["getAdminProducts"];
        put?: never;
        /**
         * 상품 검수
         * @description 관리자가 상품 검수에 대해 승인/반려 처리를 합니다.
         */
        post: operations["createProductInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/images/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presigned URL 발급
         * @description S3 이미지 업로드용 Presigned URL을 발급합니다
         */
        post: operations["getPresignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 상품 삭제
         * @description 상품 정보를 삭제합니다.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /**
         * 상품 수정
         * @description 상품 정보를 수정합니다.
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/v1/products/inspections/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 검수정보 상세조회
         * @description 관리자가 특정 상품의 검수 상세정보를 조회합니다.
         */
        get: operations["readInspection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductAuctionCreateDto: {
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            durationDays: number;
        };
        ProductCreateRequestDto: {
            name: string;
            /** @enum {string} */
            category: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            description: string;
            productAuctionCreateDto: components["schemas"]["ProductAuctionCreateDto"];
            productImageRequestDto: components["schemas"]["ProductImageRequestDto"][];
        };
        ProductImageRequestDto: {
            imgUrl: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        ProductCreateResponseDto: {
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            auctionId?: number;
            /** @enum {string} */
            inspectionStatus?: "PENDING" | "APPROVED" | "REJECTED";
        };
        SuccessResponseDtoProductCreateResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductCreateResponseDto"];
        };
        AiInternalPriceRequestDto: {
            /** @enum {string} */
            category: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            /** @enum {string} */
            condition: "MISB" | "NISB" | "MISP" | "USED";
            name: string;
            description: string;
        };
        AiInternalPriceResponseDto: {
            id?: string;
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            auctionId?: number;
            productName?: string;
            /** @enum {string} */
            productCondition?: "INSPECTION" | "MISB" | "NISB" | "MISP" | "USED";
            /** @enum {string} */
            category?: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            finalPrice?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            closedAt?: string;
            imageUrls?: string[];
            /** Format: float */
            score?: number;
        };
        SuccessResponseDtoListAiInternalPriceResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AiInternalPriceResponseDto"][];
        };
        AiExternalPriceRequestDto: {
            /** @enum {string} */
            category: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            /** @enum {string} */
            condition: "MISB" | "NISB" | "MISP" | "USED";
            name: string;
        };
        ProductInspectionRequestDto: {
            /** Format: int64 */
            productId: number;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            /** @enum {string} */
            productCondition: "INSPECTION" | "MISB" | "NISB" | "MISP" | "USED";
            reason?: string;
        };
        ProductInspectionResponseDto: {
            /** Format: int64 */
            inspectionId?: number;
            /** Format: int64 */
            productId?: number;
            /** @enum {string} */
            newStatus?: "PENDING" | "APPROVED" | "REJECTED";
            /** @enum {string} */
            productCondition?: "INSPECTION" | "MISB" | "NISB" | "MISP" | "USED";
            reason?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SuccessResponseDtoProductInspectionResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductInspectionResponseDto"];
        };
        PresignedUrlRequestDto: {
            fileName: string;
            contentType: string;
        };
        PresignedUrlResponseDto: {
            url?: string;
            s3Path?: string;
        };
        SuccessResponseDtoPresignedUrlResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PresignedUrlResponseDto"];
        };
        ProductAuctionUpdateDto: {
            /** Format: int64 */
            auctionId: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            durationDays: number;
        };
        ProductImageUpdateDto: {
            /** Format: int64 */
            id?: number;
            imgUrl: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        ProductUpdateDto: {
            name: string;
            /** @enum {string} */
            category: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            description: string;
            productAuctionUpdateDto: components["schemas"]["ProductAuctionUpdateDto"];
            productImageUpdateDtos: components["schemas"]["ProductImageUpdateDto"][];
        };
        ProductUpdateResponseDto: {
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            auctionId?: number;
        };
        SuccessResponseDtoProductUpdateResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductUpdateResponseDto"];
        };
        ProductSearchForInspectionCondition: {
            name?: string;
            /** @enum {string} */
            category?: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED";
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageDto: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        PagedResponseDtoProductResponseForInspectionDto: {
            data?: components["schemas"]["ProductResponseForInspectionDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        ProductResponseForInspectionDto: {
            /** Format: int64 */
            ProductId?: number;
            name?: string;
            sellerEmail?: string;
            /** @enum {string} */
            category?: "STARWARS" | "ORIGINAL" | "HARRYPOTTER" | "TECHNIC" | "ICONS" | "IDEAS" | "ARCHITECTURE" | "NINJAGO" | "CITY" | "ETC";
            /** @enum {string} */
            inspectionStatus?: "PENDING" | "APPROVED" | "REJECTED";
            thumbnail?: string;
        };
        SuccessResponseDtoPagedResponseDtoProductResponseForInspectionDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PagedResponseDtoProductResponseForInspectionDto"];
        };
        SuccessResponseDtoVoid: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductCreateResponseDto"];
                };
            };
        };
    };
    getInternalPriceGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiInternalPriceRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoListAiInternalPriceResponseDto"];
                };
            };
        };
    };
    getExternalPriceGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiExternalPriceRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string[];
                };
            };
        };
    };
    getAdminProducts: {
        parameters: {
            query: {
                condition: components["schemas"]["ProductSearchForInspectionCondition"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPagedResponseDtoProductResponseForInspectionDto"];
                };
            };
        };
    };
    createProductInspection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInspectionRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductInspectionResponseDto"];
                };
            };
        };
    };
    getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUrlRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPresignedUrlResponseDto"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductUpdateResponseDto"];
                };
            };
        };
    };
    readInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductInspectionResponseDto"];
                };
            };
        };
    };
}
