/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 상품 등록
         * @description 새로운 상품을 등록합니다
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/images/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presigned URL 발급
         * @description S3 이미지 업로드용 Presigned URL을 발급합니다
         */
        post: operations["getPresignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 요청
         * @description 토스페이먼츠 결제를 요청합니다
         */
        post: operations["requestPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/charges/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 승인
         * @description 토스페이먼츠 결제 승인 후 지갑에 충전합니다
         */
        post: operations["confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 낙찰 결제
         * @description 낙찰자가 최종 결제를 완료합니다 (보증금 + 잔금)
         */
        post: operations["auctionFinalPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 본인 조회
         * @description 본인의 정보를 조회합니다.
         */
        get: operations["getMe"];
        put?: never;
        /**
         * 소셜 로그인 이후 Member 생성(회원 가입)
         * @description 소셜 로그인 결과(email/provider)를 받아 회원가입 처리합니다.
         */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 회원 본인 수정
         * @description 본인의 정보를 수정합니다.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/members/me/seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 판매자 인증
         * @description 저장된 정보를 기반으로 SELLER로 업데이트 합니다
         */
        post: operations["promoteSeller"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/auctions/{productId}/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuction"];
        delete: operations["deleteAuction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProductInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/test/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 테스트 로그인
         * @description 테스트용 JWT 토큰을 발급합니다
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description 리프레시 토큰으로 액세스 토큰을 재발급합니다
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 리프레시 토큰을 폐기하고 액세스 토큰을 블랙리스트 처리합니다
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 판매 포기
         * @description 경매 실패/유찰 시 상품을 더 이상 경매에 올리지 않습니다.
         */
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관심 경매 등록
         * @description 특정 경매를 관심 목록에 추가합니다
         */
        post: operations["addBookmark"];
        /**
         * 관심 경매 해제
         * @description 특정 경매를 관심 목록에서 제거합니다
         */
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 입찰 기록 조회
         * @description 해당 경매의 실시간 입찰 내역(로그)을 조회합니다.
         */
        get: operations["getBids"];
        put?: never;
        /**
         * 입찰하기
         * @description 특정 경매에 입찰을 진행합니다. (판매자 본인 입찰 불가)
         */
        post: operations["createBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 상품 삭제
         * @description 상품 정보를 삭제합니다.
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /**
         * 상품 수정
         * @description 상품 정보를 수정합니다.
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/v1/members/me/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 회원 본인인증 정보 수정
         * @description 본인의 연락처/실명 정보를 수정합니다.
         */
        patch: operations["updateIdentity"];
        trace?: never;
    };
    "/api/v1/internal/auctions/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAuction"];
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/startTime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["deterMineStartAuction"];
        trace?: never;
    };
    "/api/v1/payments/me/wallet-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지갑 거래 내역 조회
         * @description 지갑 거래 내역을 조회합니다.
         */
        get: operations["getWalletTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/me/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 정산 내역 조회
         * @description 정산 내역을 조회합니다.
         */
        get: operations["getSettlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 입찰시 필수 정보 존재 확인
         * @description 회원 입찰시 필요 정보(주소, 본인인증) 존재 확인
         */
        get: operations["verifyParticipation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나의 판매 내역 조회
         * @description 내가 등록한 경매 물품 목록을 필터(진행중/종료 등)에 따라 조회합니다. (판매자 권한 필요)
         */
        get: operations["getMySales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 관심 경매 목록 조회
         * @description 내가 찜한 경매 목록을 조회합니다
         */
        get: operations["getMyBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 나의 입찰 내역 조회
         * @description 내가 참여한 경매 입찰 목록을 상태별로 조회합니다.
         */
        get: operations["getMyBids"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/test/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 인증 확인
         * @description 현재 인증된 사용자 정보를 확인합니다
         */
        get: operations["login_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/test/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관리자 확인
         * @description 관리자 권한을 확인합니다
         */
        get: operations["justAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 목록 조회
         * @description 검색 조건(키워드, 카테고리, 상태)과 정렬 조건에 따라 경매 목록을 조회합니다.
         */
        get: operations["getAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 상세 조회
         * @description 경매의 상세 정보를 조회합니다. (로그인 시 내 입찰 내역 포함)
         */
        get: operations["getAuctionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/subscribers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuctionSubscribers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/{auctionId}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 낙찰 상세 정보 조회
         * @description 경매 종료 후 낙찰 정보를 조회합니다. (구매자/판매자만 조회 가능)
         */
        get: operations["getAuctionOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auctions/subscribers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTotalSubscribers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductAuctionRequestDto: {
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            durationDays: number;
        };
        ProductImageRequestDto: {
            imgUrl: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        ProductRequestDto: {
            name: string;
            /** @enum {string} */
            category: "스타워즈" | "오리지널" | "해리포터";
            description: string;
            productAuctionRequestDto: components["schemas"]["ProductAuctionRequestDto"];
            productImageRequestDto: components["schemas"]["ProductImageRequestDto"][];
        };
        ProductResponseDto: {
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            auctionId?: number;
            /** @enum {string} */
            inspectionStatus?: "PENDING" | "APPROVED" | "REJECTED";
        };
        SuccessResponseDtoProductResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductResponseDto"];
        };
        PresignedUrlRequestDto: {
            fileName: string;
            contentType: string;
        };
        PresignedUrlResponseDto: {
            url?: string;
            s3Path?: string;
        };
        SuccessResponseDtoPresignedUrlResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PresignedUrlResponseDto"];
        };
        PaymentRequestDto: {
            /** Format: int32 */
            amount: number;
        };
        PaymentRequestResponseDto: {
            orderId?: string;
            /** Format: int32 */
            amount?: number;
            customerName?: string;
            customerEmail?: string;
        };
        SuccessResponseDtoPaymentRequestResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PaymentRequestResponseDto"];
        };
        PaymentConfirmRequestDto: {
            paymentKey: string;
            orderId: string;
            /** Format: int32 */
            amount: number;
        };
        PaymentConfirmResponseDto: {
            orderId?: string;
            /** Format: int32 */
            amount?: number;
            /** Format: int32 */
            balance?: number;
        };
        SuccessResponseDtoPaymentConfirmResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PaymentConfirmResponseDto"];
        };
        AuctionFinalPaymentRequestDto: {
            receiverName: string;
            phone: string;
            zipCode: string;
            address: string;
            addressDetail?: string;
            message?: string;
        };
        AuctionFinalPaymentResponseDto: {
            /** Format: int64 */
            paymentId?: number;
            /** Format: int64 */
            auctionId?: number;
            buyerId?: string;
            /** Format: int32 */
            finalPrice?: number;
            /** Format: int32 */
            depositAmount?: number;
            /** Format: int32 */
            paidAmount?: number;
            /** Format: int32 */
            balanceAfter?: number;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SuccessResponseDtoAuctionFinalPaymentResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionFinalPaymentResponseDto"];
        };
        MemberJoinRequestDto: {
            email?: string;
        };
        MemberJoinResponseDto: {
            nickname?: string;
            memberPublicId?: string;
        };
        SuccessResponseDtoMemberJoinResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MemberJoinResponseDto"];
        };
        SuccessResponseDtoVoid: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: unknown;
        };
        SuccessResponseDtoLong: {
            /** Format: int32 */
            status?: number;
            message?: string;
            /** Format: int64 */
            data?: number;
        };
        ProductInspectionRequestDto: {
            /** Format: int64 */
            productId: number;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            /** @enum {string} */
            productCondition: "INSPECTION" | "MISB" | "NISB" | "MISP" | "USED";
            reason?: string;
        };
        ProductInspectionResponseDto: {
            /** Format: int64 */
            inspectionId?: number;
            /** Format: int64 */
            productId?: number;
            /** @enum {string} */
            newStatus?: "PENDING" | "APPROVED" | "REJECTED";
            /** @enum {string} */
            productCondition?: "INSPECTION" | "MISB" | "NISB" | "MISP" | "USED";
            reason?: string;
        };
        SuccessResponseDtoProductInspectionResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductInspectionResponseDto"];
        };
        TokenIssueDto: {
            memberPublicId: string;
            role: string;
        };
        SuccessResponseDtoString: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: string;
        };
        SuccessResponseDtoMapStringString: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: {
                [key: string]: string;
            };
        };
        AuctionWithdrawResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** @enum {string} */
            beforeStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** @enum {string} */
            currentStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            message?: string;
        };
        SuccessResponseDtoAuctionWithdrawResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionWithdrawResponseDto"];
        };
        SuccessResponseDtoWishlistAddResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["WishlistAddResponseDto"];
        };
        WishlistAddResponseDto: {
            bookmarked?: boolean;
            /** Format: int64 */
            auctionId?: number;
        };
        BidRequestDto: {
            /** Format: int64 */
            bidAmount: number;
        };
        BidResponseDto: {
            /** Format: int64 */
            bidId?: number;
            /** Format: int64 */
            auctionId?: number;
            publicId?: string;
            /** Format: date-time */
            bidTime?: string;
            /** Format: int64 */
            bidAmount?: number;
            /** Format: int64 */
            updatedCurrentPrice?: number;
        };
        SuccessResponseDtoBidResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["BidResponseDto"];
        };
        ProductAuctionUpdateDto: {
            /** Format: int64 */
            auctionId: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            durationDays: number;
        };
        ProductImageUpdateDto: {
            /** Format: int64 */
            id?: number;
            imgUrl: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        ProductUpdateDto: {
            name: string;
            /** @enum {string} */
            category: "스타워즈" | "오리지널" | "해리포터";
            description: string;
            productAuctionUpdateDto: components["schemas"]["ProductAuctionUpdateDto"];
            productImageUpdateDtos: components["schemas"]["ProductImageUpdateDto"][];
        };
        ProductUpdateResponseDto: {
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            auctionId?: number;
        };
        SuccessResponseDtoProductUpdateResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["ProductUpdateResponseDto"];
        };
        MemberUpdateRequestDto: {
            nickname?: string;
            intro?: string;
            zipCode?: string;
            address?: string;
            addressDetail?: string;
            clearFields?: ("INTRO" | "ZIPCODE" | "ADDRESS" | "ADDRESS_DETAIL")[];
        };
        MemberUpdateResponseDto: {
            publicId?: string;
            email?: string;
            nickname?: string;
            intro?: string;
            address?: string;
            addressDetail?: string;
            zipCode?: string;
            contactPhone?: string;
            realName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SuccessResponseDtoMemberUpdateResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MemberUpdateResponseDto"];
        };
        MemberUpdateIdentityRequestDto: {
            realName?: string;
            contactPhone?: string;
        };
        PageDto: {
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        PagedResponseDtoWalletTransactionResponseDto: {
            data?: components["schemas"]["WalletTransactionResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        SuccessResponseDtoPagedResponseDtoWalletTransactionResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PagedResponseDtoWalletTransactionResponseDto"];
        };
        WalletTransactionResponseDto: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "TOPUP_DONE" | "DEPOSIT_HOLD" | "DEPOSIT_RELEASE" | "DEPOSIT_USED" | "DEPOSIT_FORFEITED" | "AUCTION_PAYMENT" | "REFUND_DONE" | "SETTLEMENT_PAID" | "SETTLEMENT_FEE";
            typeName?: string;
            /** Format: int32 */
            balanceDelta?: number;
            /** Format: int32 */
            holdingDelta?: number;
            /** Format: int32 */
            balance?: number;
            /** Format: int32 */
            holdingAmount?: number;
            /** @enum {string} */
            referenceType?: "PAYMENT" | "DEPOSIT" | "AUCTION_ORDER" | "SETTLEMENT" | "REFUND";
            /** Format: int64 */
            referenceId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PagedResponseDtoSettlementResponseDto: {
            data?: components["schemas"]["SettlementResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        SettlementResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            sellerId?: number;
            /** Format: int32 */
            salesAmount?: number;
            /** Format: int32 */
            feeAmount?: number;
            /** Format: int32 */
            settlementAmount?: number;
            /** @enum {string} */
            status?: "READY" | "DONE" | "FAILED";
            /** Format: date-time */
            createdAt?: string;
        };
        SuccessResponseDtoPagedResponseDtoSettlementResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["PagedResponseDtoSettlementResponseDto"];
        };
        MemberMeResponseDto: {
            publicId?: string;
            role?: string;
            email?: string;
            nickname?: string;
            intro?: string;
            address?: string;
            addressDetail?: string;
            zipCode?: string;
            contactPhoneMasked?: string;
            realNameMasked?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SuccessResponseDtoMemberMeResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["MemberMeResponseDto"];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        MySaleResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            title?: string;
            thumbnailUrl?: string;
            /** Format: int64 */
            currentPrice?: number;
            /** Format: int32 */
            bidCount?: number;
            /** @enum {string} */
            auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** @enum {string} */
            tradeStatus?: "PROCESSING" | "SUCCESS" | "FAILED";
            /** Format: date-time */
            endTime?: string;
            actionRequired?: boolean;
        };
        PagedResponseDtoMySaleResponseDto: {
            data?: components["schemas"]["MySaleResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionListResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            productName?: string;
            thumbnailUrl?: string;
            category?: string;
            /** Format: int32 */
            currentPrice?: number;
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            bidsCount?: number;
            /** @enum {string} */
            auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** Format: date-time */
            endTime?: string;
        };
        PagedResponseDtoWishlistListResponseDto: {
            data?: components["schemas"]["WishlistListResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        WishlistListResponseDto: {
            /** Format: int64 */
            bookmarkId?: number;
            auctionInfo?: components["schemas"]["AuctionListResponseDto"];
        };
        MyBidResponseDto: {
            /** Format: int64 */
            bidId?: number;
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** Format: int64 */
            bidAmount?: number;
            /** Format: date-time */
            bidTime?: string;
            /** @enum {string} */
            auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** Format: int64 */
            currentPrice?: number;
            /** Format: date-time */
            endTime?: string;
        };
        PagedResponseDtoMyBidResponseDto: {
            data?: components["schemas"]["MyBidResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionSearchCondition: {
            ids?: number[];
            keyword?: string;
            category?: string;
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            sort?: string;
        };
        PagedResponseDtoAuctionListResponseDto: {
            data?: components["schemas"]["AuctionListResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        AuctionDetailResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            productId?: number;
            /** @enum {string} */
            status?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int64 */
            remainingSeconds?: number;
            price?: components["schemas"]["PriceInfo"];
            bid?: components["schemas"]["BidInfo"];
            myParticipation?: components["schemas"]["MyParticipationInfo"];
        };
        BidInfo: {
            canBid?: boolean;
            /** Format: int32 */
            minBidPrice?: number;
            /** Format: int64 */
            highestBidderId?: number;
            isMyHighestBid?: boolean;
        };
        MyParticipationInfo: {
            hasBid?: boolean;
            /** Format: int32 */
            myLastBidPrice?: number;
        };
        PriceInfo: {
            /** Format: int32 */
            startPrice?: number;
            /** Format: int32 */
            currentPrice?: number;
            /** Format: int32 */
            tickSize?: number;
        };
        SuccessResponseDtoAuctionDetailResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionDetailResponseDto"];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        AuctionOrderResponseDto: {
            /** Format: int64 */
            orderId?: number;
            /** Format: int64 */
            auctionId?: number;
            viewerRole?: string;
            /** @enum {string} */
            orderStatus?: "PROCESSING" | "SUCCESS" | "FAILED";
            statusDescription?: string;
            /** Format: date-time */
            createdAt?: string;
            productInfo?: components["schemas"]["ProductInfo"];
            paymentInfo?: components["schemas"]["PaymentInfo"];
            trader?: components["schemas"]["TraderInfo"];
            shippingInfo?: components["schemas"]["ShippingInfo"];
        };
        PaymentInfo: {
            /** Format: int32 */
            finalPrice?: number;
            /** Format: int32 */
            depositUsed?: number;
            /** Format: int32 */
            paymentAmount?: number;
        };
        ProductInfo: {
            title?: string;
            thumbnailUrl?: string;
        };
        ShippingInfo: {
            receiverName?: string;
            address?: string;
            trackingNumber?: string;
        };
        SuccessResponseDtoAuctionOrderResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["AuctionOrderResponseDto"];
        };
        TraderInfo: {
            nickname?: string;
            contact?: string;
        };
        BidLogResponseDto: {
            /** Format: int64 */
            id?: number;
            publicId?: string;
            /** Format: date-time */
            bidTime?: string;
            /** Format: int64 */
            bidAmount?: number;
        };
        PagedResponseDtoBidLogResponseDto: {
            data?: components["schemas"]["BidLogResponseDto"][];
            pageDto?: components["schemas"]["PageDto"];
        };
        SuccessResponseDtoWishlistRemoveResponseDto: {
            /** Format: int32 */
            status?: number;
            message?: string;
            data?: components["schemas"]["WishlistRemoveResponseDto"];
        };
        WishlistRemoveResponseDto: {
            removed?: boolean;
            /** Format: int64 */
            bookmarkId?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createProduct: {
        parameters: {
            query: {
                publicId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductResponseDto"];
                };
            };
        };
    };
    getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUrlRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPresignedUrlResponseDto"];
                };
            };
        };
    };
    requestPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPaymentRequestResponseDto"];
                };
            };
        };
    };
    confirmPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPaymentConfirmResponseDto"];
                };
            };
        };
    };
    auctionFinalPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionFinalPaymentRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionFinalPaymentResponseDto"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberMeResponseDto"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberJoinRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberJoinResponseDto"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberUpdateResponseDto"];
                };
            };
        };
    };
    promoteSeller: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductAuctionRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoLong"];
                };
            };
        };
    };
    deleteAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    createProductInspection: {
        parameters: {
            query: {
                inspectorId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInspectionRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductInspectionResponseDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIssueDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoString"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMapStringString"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionWithdrawResponseDto"];
                };
            };
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoWishlistAddResponseDto"];
                };
            };
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoWishlistRemoveResponseDto"];
                };
            };
        };
    };
    getBids: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoBidLogResponseDto"];
                };
            };
        };
    };
    createBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoBidResponseDto"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query: {
                publicId: string;
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query: {
                publicId: string;
            };
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoProductUpdateResponseDto"];
                };
            };
        };
    };
    updateIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateIdentityRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoMemberUpdateResponseDto"];
                };
            };
        };
    };
    updateAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductAuctionUpdateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoLong"];
                };
            };
        };
    };
    deterMineStartAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoLong"];
                };
            };
        };
    };
    getWalletTransactions: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                transactionType?: "TOPUP_DONE" | "DEPOSIT_HOLD" | "DEPOSIT_RELEASE" | "DEPOSIT_USED" | "DEPOSIT_FORFEITED" | "AUCTION_PAYMENT" | "REFUND_DONE" | "SETTLEMENT_PAID" | "SETTLEMENT_FEE";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPagedResponseDtoWalletTransactionResponseDto"];
                };
            };
        };
    };
    getSettlements: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: "READY" | "DONE" | "FAILED";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoPagedResponseDtoSettlementResponseDto"];
                };
            };
        };
    };
    verifyParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoVoid"];
                };
            };
        };
    };
    getMySales: {
        parameters: {
            query: {
                filter?: "ALL" | "ONGOING" | "COMPLETED" | "ACTION_REQUIRED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoMySaleResponseDto"];
                };
            };
        };
    };
    getMyBookmarks: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoWishlistListResponseDto"];
                };
            };
        };
    };
    getMyBids: {
        parameters: {
            query: {
                auctionStatus?: "SCHEDULED" | "IN_PROGRESS" | "ENDED" | "WITHDRAWN";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoMyBidResponseDto"];
                };
            };
        };
    };
    login_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoString"];
                };
            };
        };
    };
    justAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoString"];
                };
            };
        };
    };
    getAuctions: {
        parameters: {
            query: {
                condition: components["schemas"]["AuctionSearchCondition"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedResponseDtoAuctionListResponseDto"];
                };
            };
        };
    };
    getAuctionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionDetailResponseDto"];
                };
            };
        };
    };
    getAuctionSubscribers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getAuctionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SuccessResponseDtoAuctionOrderResponseDto"];
                };
            };
        };
    };
    getTotalSubscribers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
}
