/**
 * This file was auto-generated by scripts/generate-api.mjs.
 * Do not make direct changes to the file.
 */

import type { paths as memberPaths, components as memberComponents } from "./schemas/member";
import type { paths as authPaths, components as authComponents } from "./schemas/auth";
import type { paths as paymentPaths, components as paymentComponents } from "./schemas/payment";
import type { paths as auctionPaths, components as auctionComponents } from "./schemas/auction";
import type { paths as productPaths, components as productComponents } from "./schemas/product";
import type { paths as notificationPaths, components as notificationComponents } from "./schemas/notification";

export type paths = memberPaths & authPaths & paymentPaths & auctionPaths & productPaths & notificationPaths;

export interface components {
  schemas: memberComponents['schemas'] & authComponents['schemas'] & paymentComponents['schemas'] & auctionComponents['schemas'] & productComponents['schemas'] & notificationComponents['schemas'];
}
