import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SERVICES = [
    { name: 'member', port: 8081 },
    { name: 'auth', port: 8089 },
    { name: 'payment', port: 8082 },
    { name: 'auction', port: 8083 },
    { name: 'product', port: 8084 },
    { name: 'notification', port: 8085 },
];

const OUTPUT_DIR = path.resolve(__dirname, '../src/api/schemas');
const FINAL_SCHEMA_PATH = path.resolve(__dirname, '../src/api/schema.d.ts');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('🚀 Starting API generation for services...');

const generatedServices = [];

for (const service of SERVICES) {
    const url = `http://localhost:${service.port}/api-docs`;
    const outputPath = path.join(OUTPUT_DIR, `${service.name}.d.ts`);

    try {
        console.log(`⏳ Generating schema for ${service.name} (${url})...`);
        execSync(`npm exec openapi-typescript -- ${url} -o ${outputPath}`, { stdio: 'inherit' });
        generatedServices.push(service.name);
        console.log(`✅ Automatically generated ${service.name} schema.`);
    } catch (error) {
        console.error(`❌ Failed to generate schema for ${service.name}: ${error.message}`);
        // We continue even if one fails, but you might want to stop in strict mode
    }
}

// Generate the aggregator file
console.log('🔄 Merging schemas into src/api/schema.d.ts...');

const imports = generatedServices.map(name => `import type { paths as ${name}Paths, components as ${name}Components } from "./schemas/${name}";`).join('\n');

const pathIntersections = generatedServices.map(name => `${name}Paths`).join(' & ');
const schemaIntersections = generatedServices.map(name => `${name}Components['schemas']`).join(' & ');

const content = `/**
 * This file was auto-generated by scripts/generate-api.mjs.
 * Do not make direct changes to the file.
 */

${imports}

export type paths = ${pathIntersections || '{}'};

export interface components {
  schemas: ${schemaIntersections || '{}'};
}
`;

fs.writeFileSync(FINAL_SCHEMA_PATH, content);
console.log('✨ API generation complete!');
