apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rarego
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: frontend
          image: rarego-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: rarego
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
